package com.mahalak.media.controller;
import com.mahalak.media.IServices.ICommerceService; import com.mahalak.media.dto.request.*; import com.mahalak.media.dto.response.CheckoutPreviewResponse; import com.mahalak.media.dto.wrapper.ApiResponse; import com.mahalak.media.entity.*; import lombok.RequiredArgsConstructor; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import jakarta.validation.Valid; import java.util.*;
@RestController @RequestMapping("/rest/commerce") @RequiredArgsConstructor public class CommerceController { private final ICommerceService service;
 @PostMapping("/checkout/preview") public ResponseEntity<ApiResponse<CheckoutPreviewResponse>> preview(@Valid @RequestBody CheckoutPreviewRequest r){return ResponseEntity.ok(ApiResponse.success(200,"Checkout preview fetched.",service.preview(r)));}
 @PostMapping("/admin/coupon") public ResponseEntity<ApiResponse<Coupon>> coupon(@RequestBody CouponRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(ApiResponse.success(201,"Coupon saved.",service.saveCoupon(r,null)));}
 @PutMapping("/admin/coupon") public ResponseEntity<ApiResponse<Coupon>> couponUpdate(@RequestParam String couponId,@RequestBody CouponRequest r){return ResponseEntity.ok(ApiResponse.success(200,"Coupon updated.",service.saveCoupon(r,couponId)));}
 @GetMapping("/coupon") public ResponseEntity<ApiResponse<List<Coupon>>> coupons(){return ResponseEntity.ok(ApiResponse.success(200,"Coupons fetched.",service.coupons()));}
 @PostMapping("/admin/shipment") public ResponseEntity<ApiResponse<Shipment>> shipment(@RequestParam String orderId,@RequestBody ShipmentRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(ApiResponse.success(201,"Shipment created.",service.createShipment(orderId,r)));}
 @GetMapping("/shipment") public ResponseEntity<ApiResponse<Shipment>> shipmentGet(@RequestParam String orderId){return ResponseEntity.ok(ApiResponse.success(200,"Shipment fetched.",service.getShipment(orderId)));}
 @PostMapping("/refund/request") public ResponseEntity<ApiResponse<Refund>> refund(@RequestParam String orderId,@Valid @RequestBody RefundRequest r){return ResponseEntity.status(HttpStatus.CREATED).body(ApiResponse.success(201,"Refund requested.",service.requestRefund(orderId,r)));}
 @PatchMapping("/admin/refund") public ResponseEntity<ApiResponse<Refund>> refundProcess(@RequestParam String refundId,@RequestParam boolean approve){return ResponseEntity.ok(ApiResponse.success(200,"Refund processed.",service.processRefund(refundId,approve)));}
 @GetMapping("/admin/inventory") public ResponseEntity<ApiResponse<List<InventoryMovement>>> inventory(@RequestParam String productId){return ResponseEntity.ok(ApiResponse.success(200,"Inventory history fetched.",service.inventory(productId)));}
}
