package com.mahalak.media.servicesImpl;
import com.mahalak.media.IServices.ICommerceService; import com.mahalak.media.auth.SecurityUtil; import com.mahalak.media.dto.request.*; import com.mahalak.media.dto.response.CheckoutPreviewResponse; import com.mahalak.media.entity.*; import com.mahalak.media.enums.*; import com.mahalak.media.exception.*; import com.mahalak.media.framework.GoogleEntityManager; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import java.time.LocalDateTime; import java.util.*;
@Service @RequiredArgsConstructor public class CommerceServiceImpl implements ICommerceService {
 private final GoogleEntityManager em;
 public CheckoutPreviewResponse preview(CheckoutPreviewRequest r){ String uid=SecurityUtil.getCurrentUserId().toString(); Address a=em.findById(Address.class,r.getAddressId()).orElseThrow(()->new ResourceNotFoundException("Address not found.")); if(!uid.equals(a.getUserId())||Boolean.TRUE.equals(a.getIsAddressDeleted())) throw new BadRequestException("Invalid address."); double total=em.findAll(Cart.class).stream().filter(c->uid.equals(c.getUserId())).mapToDouble(c->{Product p=em.findById(Product.class,c.getProductId()).orElseThrow(()->new ResourceNotFoundException("Product not found.")); return p.getPrice()*c.getQuantity();}).sum(); if(total==0)throw new BadRequestException("Cart is empty."); LocalDateTime now=LocalDateTime.now(); double tax=total*rate(TaxRule.class,now)/100, disc=total*rate(DiscountRule.class,now)/100, ship=total*rate(ShippingRule.class,now)/100, coupon=couponDiscount(r.getCouponCode(),uid,total,now); return CheckoutPreviewResponse.builder().productTotal(total).taxAmount(tax).ruleDiscountAmount(disc).couponDiscountAmount(coupon).shippingAmount(ship).finalAmount(total+tax+ship-disc-coupon).build(); }
 public Coupon saveCoupon(CouponRequest r,String id){ if(r.getCode()==null||r.getCode().isBlank()||r.getDiscountPercent()==null||r.getDiscountPercent()<0||r.getDiscountPercent()>100)throw new BadRequestException("Invalid coupon."); Coupon c=id==null?Coupon.builder().createdAt(LocalDateTime.now()).build():em.findById(Coupon.class,id).orElseThrow(()->new ResourceNotFoundException("Coupon not found.")); c.setCode(r.getCode().trim().toUpperCase());c.setDiscountPercent(r.getDiscountPercent());c.setMinOrderAmount(r.getMinOrderAmount()==null?0:r.getMinOrderAmount());c.setMaxDiscountAmount(r.getMaxDiscountAmount());c.setMaxUsesPerUser(r.getMaxUsesPerUser()==null?1:r.getMaxUsesPerUser());c.setActive(Boolean.TRUE.equals(r.getActive()));c.setStartDate(r.getStartDate());c.setEndDate(r.getEndDate());c.setUpdatedAt(LocalDateTime.now());if(id==null)em.save(c);else em.update(c);return c; }
 public List<Coupon> coupons(){return em.findAll(Coupon.class);}
 public Shipment createShipment(String orderId,ShipmentRequest r){Order o=order(orderId);if(!OrderStatus.PROCESSING.name().equals(o.getOrderStatus()))throw new BadRequestException("Only processing orders can be shipped.");Shipment s=Shipment.builder().orderId(orderId).courierName(r.getCourierName()).trackingNumber(r.getTrackingNumber()).trackingUrl(r.getTrackingUrl()).estimatedDelivery(r.getEstimatedDelivery()).shippedAt(LocalDateTime.now()).createdAt(LocalDateTime.now()).updatedAt(LocalDateTime.now()).build();em.save(s);o.setOrderStatus(OrderStatus.SHIPPED.name());o.setUpdatedAt(LocalDateTime.now());em.update(o);history(o,"PROCESSING","SHIPPED","Shipment created");return s;}
 public Shipment getShipment(String orderId){return em.findAll(Shipment.class).stream().filter(s->orderId.equals(s.getOrderId())).findFirst().orElseThrow(()->new ResourceNotFoundException("Shipment not found."));}
 public Refund requestRefund(String orderId,RefundRequest r){Order o=order(orderId);if(!SecurityUtil.getCurrentUserId().toString().equals(o.getUserId()))throw new BadRequestException("Unauthorized.");if(!OrderStatus.CONFIRMED.name().equals(o.getOrderStatus()))throw new BadRequestException("Only confirmed unshipped orders can be refunded.");Payment p=em.findAll(Payment.class).stream().filter(x->orderId.equals(x.getOrderId())).findFirst().orElseThrow(()->new ResourceNotFoundException("Payment not found."));if(!PaymentStatus.VERIFIED.name().equals(p.getPaymentStatus()))throw new BadRequestException("Only paid online orders can be refunded.");Refund x=Refund.builder().orderId(orderId).paymentId(p.getPaymentId()).amount(o.getFinalAmount()).status(RefundStatus.REQUESTED.name()).reason(r.getReason()).createdAt(LocalDateTime.now()).updatedAt(LocalDateTime.now()).build();em.save(x);return x;}
 public Refund processRefund(String id,boolean approve){Refund r=em.findById(Refund.class,id).orElseThrow(()->new ResourceNotFoundException("Refund not found."));if(!RefundStatus.REQUESTED.name().equals(r.getStatus()))throw new BadRequestException("Refund already processed.");r.setStatus((approve?RefundStatus.APPROVED:RefundStatus.REJECTED).name());r.setProcessedBy(SecurityUtil.getCurrentUserId().toString());r.setProcessedAt(LocalDateTime.now());r.setUpdatedAt(LocalDateTime.now());em.update(r);return r;}
 public List<InventoryMovement> inventory(String productId){return em.findAll(InventoryMovement.class).stream().filter(x->productId.equals(x.getProductId())).toList();}
 private Order order(String id){return em.findById(Order.class,id).orElseThrow(()->new ResourceNotFoundException("Order not found."));} private void history(Order o,String f,String t,String n){em.save(OrderStatusHistory.builder().orderId(o.getOrderId()).fromStatus(f).toStatus(t).changedBy(SecurityUtil.getCurrentUserId().toString()).note(n).changedAt(LocalDateTime.now()).build());}
 private double couponDiscount(String code,String uid,double total,LocalDateTime now){if(code==null||code.isBlank())return 0;Coupon c=em.findAll(Coupon.class).stream().filter(x->code.trim().equalsIgnoreCase(x.getCode())).findFirst().orElseThrow(()->new BadRequestException("Coupon not found."));if(!Boolean.TRUE.equals(c.getActive())||total<c.getMinOrderAmount()||(c.getStartDate()!=null&&now.isBefore(c.getStartDate()))||(c.getEndDate()!=null&&now.isAfter(c.getEndDate())))throw new BadRequestException("Coupon is not applicable."); long used=em.findAll(Order.class).stream().filter(o->uid.equals(o.getUserId())&&code.equalsIgnoreCase(o.getCouponCode())).count();if(used>=c.getMaxUsesPerUser())throw new BadRequestException("Coupon usage limit reached.");double d=total*c.getDiscountPercent()/100;return c.getMaxDiscountAmount()==null?d:Math.min(d,c.getMaxDiscountAmount());}
 private <T> double rate(Class<T> c,LocalDateTime n){return em.findAll(c).stream().mapToDouble(x->{if(x instanceof TaxRule r)return active(r.getActive(),r.getStartDate(),r.getEndDate(),n)?r.getRate():0;if(x instanceof DiscountRule r)return active(r.getActive(),r.getStartDate(),r.getEndDate(),n)?r.getRate():0;ShippingRule r=(ShippingRule)x;return active(r.getActive(),r.getStartDate(),r.getEndDate(),n)?r.getRate():0;}).sum();} private boolean active(Boolean a,LocalDateTime s,LocalDateTime e,LocalDateTime n){return Boolean.TRUE.equals(a)&&(s==null||!n.isBefore(s))&&(e==null||!n.isAfter(e));}
}
